function SpaceShip(){
this.x=0;
this.y=0;
this.width=25;
this.height=25;
this.rotation=0;
this.showFlame=false;
this.off=false;
}
SpaceShip.prototype.draw=function(ctx){
ctx.save();
ctx.beginPath();
ctx.translate(this.x,this.y);
ctx.rotate(this.rotation);
ctx.strokeStyle="#fff";
ctx.moveTo(10,0);
ctx.lineTo(-10,10);
ctx.lineTo(-5,0);
ctx.lineTo(-10,-10);
ctx.lineTo(10,0);
ctx.closePath();
ctx.stroke();
if(this.showFlaem==true){
ctx.save();
ctx.beginPath();
ctx.strokeStyle="#f69";
ctx.moveTo(-7.5,-5);
ctx.lineTo(-15,0);
ctx.lineTo(-7.5,5);
ctx.stroke();
ctx.restore();
}
ctx.restore();
}
SpaceShip.prototype.fire=function(ctx){
for(var i=0;i<bullets.length;i++){
if(!bullets[i].off){
ctx.save();
ctx.beginPath();
ctx.moveTo(bullets[i].x,bullets[i].y);
ctx.fillStyle="#fff";
ctx.fillRect(bullets[i].x,bullets[i].y-=10,bullets[i].width,bullets[i].height);
ctx.closePath();
ctx.restore();
}
}
}
SpaceShip.prototype.createBullet=function(){
var bullet={
x:this.x-1,
y:this.y-25,
width:2,
height:10
}
bullets.push(bullet)
}
